FROM jenkins/jenkins:lts

USER root

# Установка пакетов + Docker CLI + Docker Compose + Kubectl
RUN apt-get update && \
    apt-get install -y wget unzip python3 python3-pip python3-venv curl && \
    # Docker
    wget https://download.docker.com/linux/static/stable/x86_64/docker-24.0.5.tgz -O /tmp/docker.tgz && \
    tar -xzf /tmp/docker.tgz -C /tmp && \
    mv /tmp/docker/docker /usr/local/bin/ && \
    rm -rf /tmp/docker.tgz /tmp/docker && \
    # Docker Compose
    wget https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -O /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    # Kubectl 
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Права доступа
RUN groupadd -f docker && usermod -aG docker jenkins && \
    rm -rf /var/lib/apt/lists/*

USER jenkins